#Project properties
project.organization=Paderborn Center for Parallel Computing | Efficient Computing and Storage Group Johannes Gutenberg-Universitaet Mainz
project.name=FS-C
sbt.version=1.10.11
project.version=0.4.0
build.scala.versions=3.6.4
project.initialize=false
